# Generated by Django 3.2.4 on 2021-07-13 14:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0002_auto_20210711_0148'),
    ]

    operations = [
        migrations.AddField(
            model_name='product1',
            name='likes',
            field=models.ManyToManyField(related_name='blog_like', to=settings.AUTH_USER_MODEL),
        ),
    ]
