# Generated by Django 3.2.5 on 2021-08-12 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.URLField(blank=True, default=None, null=True)),
                ('price_amazon', models.DecimalField(blank=True, decimal_places=2, default=True, max_digits=10)),
                ('price_ebay', models.DecimalField(blank=True, decimal_places=2, default=True, max_digits=10)),
                ('condition', models.CharField(max_length=25)),
                ('amazon_url', models.URLField(blank=True, default='None', null=True)),
                ('ebay_url', models.URLField(blank=True, default='None', null=True)),
                ('slug', models.SlugField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Products',
            },
        ),
    ]
