# Generated by Django 3.2.4 on 2021-07-31 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='price_amazon',
        ),
        migrations.AddField(
            model_name='product',
            name='price_ebay',
            field=models.DecimalField(decimal_places=2, default=99.87, max_digits=4),
            preserve_default=False,
        ),
    ]
