# Generated by Django 3.2.5 on 2021-08-05 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.AddField(
            model_name='product',
            name='image_amazon',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='product',
            name='image_ebay',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='product',
            name='price_amazon',
            field=models.DecimalField(blank=True, decimal_places=2, default=True, max_digits=4),
        ),
        migrations.AddField(
            model_name='product',
            name='price_ebay',
            field=models.DecimalField(blank=True, decimal_places=2, default=True, max_digits=4),
        ),
    ]
