# Generated by Django 3.2.5 on 2021-08-07 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210805_1200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image_amazon',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image_ebay',
        ),
        migrations.AddField(
            model_name='product',
            name='amazon_url',
            field=models.URLField(blank=True, default='None', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='ebay_url',
            field=models.URLField(blank=True, default='None', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_amazon',
            field=models.DecimalField(blank=True, decimal_places=2, default=True, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_ebay',
            field=models.DecimalField(blank=True, decimal_places=2, default=True, max_digits=10),
        ),
    ]
